//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int MinimumTaineeAge {
            get {
                return ((int)(this["MinimumTaineeAge"]));
            }
            set {
                this["MinimumTaineeAge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int MinimumTesterAge {
            get {
                return ((int)(this["MinimumTesterAge"]));
            }
            set {
                this["MinimumTesterAge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int MaximumTestsInWeek {
            get {
                return ((int)(this["MaximumTestsInWeek"]));
            }
            set {
                this["MaximumTestsInWeek"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int MaximumTesterAge {
            get {
                return ((int)(this["MaximumTesterAge"]));
            }
            set {
                this["MaximumTesterAge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int MinimumDaysBetweenTests {
            get {
                return ((int)(this["MinimumDaysBetweenTests"]));
            }
            set {
                this["MinimumDaysBetweenTests"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int MinimumDrivingLessons {
            get {
                return ((int)(this["MinimumDrivingLessons"]));
            }
            set {
                this["MinimumDrivingLessons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int PassingGrade {
            get {
                return ((int)(this["PassingGrade"]));
            }
            set {
                this["PassingGrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:30:00")]
        public global::System.TimeSpan TestTimeSpan {
            get {
                return ((global::System.TimeSpan)(this["TestTimeSpan"]));
            }
            set {
                this["TestTimeSpan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int WorkStartHour {
            get {
                return ((int)(this["WorkStartHour"]));
            }
            set {
                this["WorkStartHour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19")]
        public int WorkEndHour {
            get {
                return ((int)(this["WorkEndHour"]));
            }
            set {
                this["WorkEndHour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int FridayWorkEndHour {
            get {
                return ((int)(this["FridayWorkEndHour"]));
            }
            set {
                this["FridayWorkEndHour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("avraham224@gmail.com")]
        public string SenderEmailAddress {
            get {
                return ((string)(this["SenderEmailAddress"]));
            }
            set {
                this["SenderEmailAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hluuarmauvxfpzfs")]
        public string EmailServerPasword {
            get {
                return ((string)(this["EmailServerPasword"]));
            }
            set {
                this["EmailServerPasword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyBzz5Hd1UJW7NKf27JvD4HB0nBfLM4qfJQ")]
        public string GoogleMapsApiKey {
            get {
                return ((string)(this["GoogleMapsApiKey"]));
            }
            set {
                this["GoogleMapsApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")]
        public string SMTP_Server {
            get {
                return ((string)(this["SMTP_Server"]));
            }
            set {
                this["SMTP_Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public int SMTP_Port {
            get {
                return ((int)(this["SMTP_Port"]));
            }
            set {
                this["SMTP_Port"] = value;
            }
        }
    }
}
